### ISSUE TITLE
howto add one image or delete one image from embed via cli or api?

### ISSUE THREAD

**Issue by gnulife** [tikendraw/reverse-image-search#6]
thanks

**Comment by tikendraw** [comment]
try, removing the image from the directory and updating the embedding.

**Comment by tikendraw** [comment]
you can't add/delete just one image. you can add image to existing embedded directory and update the embedding. or add  image to a new directory and embed the directory.

**Comment by gnulife** [comment]
> you can't add/delete just one image. you can add image to existing embedded directory and update the embedding. or add image to a new directory and embed the directory.

thanks for your reply quickly. so i do it like this is right?
1. mv a.jpg /home/username/myembedded_dir/ && image_search_cli embed update -d /home/username/myembedded_dir/
2. rm /home/username/myembedded_dir/a.jpg && image_search_cli embed update -d /home/username/myembedded_dir/

**Comment by tikendraw** [comment]
both works.
